### ISSUE TITLE
AnswerCallbackQuery URL_INVALID

### ISSUE THREAD

**Issue by AlexanderShniperson** [mukel/telegrambot4s#36]
here is the code
```
object PokerTelegramBot extends TelegramBot with Polling with Messages {
  lazy val token = "SOME_TOKEN"

  override def receiveMessage(msg: Message) = {
    msg.text.foreach {
      case "/start" ⇒
        println("start handled")
        val inlineBtns = InlineKeyboardMarkup(Seq(Seq(InlineKeyboardButton(
          text = "Play now!",
          callbackData = Some("{ game_short_name: \"cpptest\" }")))))
        reply("To play game press button", replyMarkup = Some(inlineBtns))(msg)

      case any ⇒ println(s"unhandled message <$any>")
    }
  }

  override def receiveCallbackQuery(callbackQuery: CallbackQuery) = {
    println(s"gameShortName: ${callbackQuery.gameShortName}")
    println(s"data: ${callbackQuery.data}")
    callbackQuery.data.foreach { data ⇒
      if (data.contains("game_short_name: \"cpptest\""))
        request(AnswerCallbackQuery(callbackQuery.id, url = Some("http://google.com")))
    }
  }
}
```
exception happens
```
info.mukel.telegrambot4s.api.TelegramApiException: Bad Request: URL_INVALID
        at info.mukel.telegrambot4s.clients.AkkaClient$$anonfun$apply$3.apply(AkkaClient.scala:56)
        at info.mukel.telegrambot4s.clients.AkkaClient$$anonfun$apply$3.apply(AkkaClient.scala:51)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by mukel** [comment]
From the Telegram [doc](https://core.telegram.org/bots/api#answercallbackquery):

> URL that will be opened by the user's client. 
> If you have created a Game and accepted the conditions via @Botfather,
> specify the URL that opens your game – note that this will only work if the query comes from a 
> callback_game button.
> 
> Otherwise, you may use links like t.me/your_bot?start=XXXX that open your bot with a parameter.

There's a URL validation/restriction on the Telegram side.
  - You can only include arbitrary URLs to answer callback queries generated by game buttons e.g. `InlineKeyboardButton.callbackGame(...)`
  - For data callback queries (from `InlineKeyboardButton.callbackData(...)` buttons), you can answer with URLs like `https://t.me/YourBot?start=1234` (see [Deep Linking](https://core.telegram.org/bots#deep-linking))

**Comment by mukel** [comment]
A `TelegramApiException`  means an error on the Telegram side (usually invalid/malformed input, limit rate exceeded...). It basically wraps the error message returned by Telegram.

It does not cover 400s, 500s, network, timeouts, serialization... related errors.

**Comment by AlexanderShniperson** [comment]
@mukel ok thanks for explanation
